"""migration_init

Revision ID: ab6a9c833d5f
Revises: 
Create Date: 2025-06-06 13:24:27.048956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6a9c833d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('name_start', sa.String(length=255), nullable=False),
    sa.Column('name_end', sa.String(length=255), nullable=False),
    sa.Column('dots_start', sa.JSON(), nullable=False),
    sa.Column('dots_end', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_routes_id'), 'bus_routes', ['id'], unique=False)
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('coordinate', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_stops_id'), 'bus_stops', ['id'], unique=False)
    op.create_table('food_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_categories_id'), 'food_categories', ['id'], unique=False)
    op.create_table('bus_route_stops',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['bus_stops.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'stop_id')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_category_id'), 'foods', ['category_id'], unique=False)
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_table('food_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=255), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_scores_food_id'), 'food_scores', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_scores_id'), 'food_scores', ['id'], unique=False)
    op.create_index(op.f('ix_food_scores_score'), 'food_scores', ['score'], unique=False)
    op.create_index(op.f('ix_food_scores_user_id'), 'food_scores', ['user_id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_date'), 'menu', ['date'], unique=False)
    op.create_index(op.f('ix_menu_food_id'), 'menu', ['food_id'], unique=False)
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_food_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_date'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_food_scores_user_id'), table_name='food_scores')
    op.drop_index(op.f('ix_food_scores_score'), table_name='food_scores')
    op.drop_index(op.f('ix_food_scores_id'), table_name='food_scores')
    op.drop_index(op.f('ix_food_scores_food_id'), table_name='food_scores')
    op.drop_table('food_scores')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_category_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_table('bus_route_stops')
    op.drop_index(op.f('ix_food_categories_id'), table_name='food_categories')
    op.drop_table('food_categories')
    op.drop_index(op.f('ix_bus_stops_id'), table_name='bus_stops')
    op.drop_table('bus_stops')
    op.drop_index(op.f('ix_bus_routes_id'), table_name='bus_routes')
    op.drop_table('bus_routes')
    # ### end Alembic commands ###
